# Use root/example as user/password credentials
version: '3.7'

services:

  db:
    image: mariadb
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: realworld
      MARIADB_USER: realworld
      MARIADB_PASSWORD: realworld
      MARIADB_ROOT_PASSWORD: 123456
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d:ro

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  mariadb-data:
    driver: local